
**********************************************************************

Test build
build project using make

**********************************************************************
Trying to clean project using make clean
make clean
rm *.o
rm: cannot remove `*.o': No such file or directory
make: *** [clean] Error 1
test build FAILED
Trying to build project using make
make
gcc -c -fpic mem1.c -m32
mem1.c: In function ‘Mem_Init’:
mem1.c:48: warning: comparison between pointer and integer
gcc -shared -o libmem.so mem1.o -m32
gcc mem_test.c -lmem -L. -o myprogram -m32
./libmem.so: undefined reference to `GETSIZE'
collect2: ld returned 1 exit status
make: *** [test_prog] Error 1
test build FAILED


test build FAILED
 (build project using make)
 make clean failed (error 2)
 make failed (error 2)


**********************************************************************

Test init_bestfit
call Mem_Init with size = 1 page and policy = P_BESTFIT

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_bestfit


test init_bestfit PASSED
 (call Mem_Init with size = 1 page and policy = P_BESTFIT)


**********************************************************************

Test init_worstfit
call Mem_Init with size = 5 pages and policy = P_WORSTFIT

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_worstfit
init_worstfit: init_worstfit.c:7: main: Assertion `Mem_Init(20480,(1)) == 0' failed.
test init_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_worstfit returned incorrect status code. Expected 0 got -6


test init_worstfit FAILED
 (call Mem_Init with size = 5 pages and policy = P_WORSTFIT)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test init_firstfit
call Mem_Init with size = 10 pages and policy = P_FIRSTFIT

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_firstfit
init_firstfit: init_firstfit.c:7: main: Assertion `Mem_Init(40960,(2)) == 0' failed.
test init_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_firstfit returned incorrect status code. Expected 0 got -6


test init_firstfit FAILED
 (call Mem_Init with size = 10 pages and policy = P_FIRSTFIT)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test init_pageround
init that should be rounded up to 1 page

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_pageround


test init_pageround PASSED
 (init that should be rounded up to 1 page)


**********************************************************************

Test init_zerosize
call Mem_Init with zero size

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_zerosize
invalid sizeOfRegion
: Success


test init_zerosize PASSED
 (call Mem_Init with zero size)


**********************************************************************

Test init_negsize
call Mem_Init with negative size

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_negsize
invalid sizeOfRegion
: Success


test init_negsize PASSED
 (call Mem_Init with negative size)


**********************************************************************

Test init_negpolicy
call Mem_Init with a negative policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_negpolicy
bad policy
: Success


test init_negpolicy PASSED
 (call Mem_Init with a negative policy)


**********************************************************************

Test init_badpolicy
call Mem_Init with an invalid positive policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_badpolicy
bad policy
: Success


test init_badpolicy PASSED
 (call Mem_Init with an invalid positive policy)


**********************************************************************

Test init_twice
call Mem_Init twice

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/init_twice
init_twice: init_twice.c:8: main: Assertion `Mem_Init(500,(0)) == -1' failed.
test init_twice FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_twice returned incorrect status code. Expected 0 got -6


test init_twice FAILED
 (call Mem_Init twice)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_twice returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc_bestfit
a simple 8 byte allocation with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_bestfit
alloc_bestfit: alloc_bestfit.c:9: main: Assertion `ptr != ((void *)0)' failed.
test alloc_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_bestfit returned incorrect status code. Expected 0 got -6


test alloc_bestfit FAILED
 (a simple 8 byte allocation with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc_worstfit
a simple 8 byte allocation with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_worstfit
alloc_worstfit: alloc_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test alloc_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_worstfit returned incorrect status code. Expected 0 got -6


test alloc_worstfit FAILED
 (a simple 8 byte allocation with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc_firstfit
a simple 8 byte allocation with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_firstfit
alloc_firstfit: alloc_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test alloc_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_firstfit returned incorrect status code. Expected 0 got -6


test alloc_firstfit FAILED
 (a simple 8 byte allocation with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc_nospace_bestfit
allocation is too big to fit for bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_bestfit


test alloc_nospace_bestfit PASSED
 (allocation is too big to fit for bestfit policy)


**********************************************************************

Test alloc_nospace_worstfit
allocation is too big to fit for worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_worstfit
alloc_nospace_worstfit: alloc_nospace_worstfit.c:7: main: Assertion `Mem_Init(4096, (1)) == 0' failed.
test alloc_nospace_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_worstfit returned incorrect status code. Expected 0 got -6


test alloc_nospace_worstfit FAILED
 (allocation is too big to fit for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc_nospace_firstfit
allocation is too big to fit for firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_firstfit
alloc_nospace_firstfit: alloc_nospace_firstfit.c:7: main: Assertion `Mem_Init(4096, (2)) == 0' failed.
test alloc_nospace_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_firstfit returned incorrect status code. Expected 0 got -6


test alloc_nospace_firstfit FAILED
 (allocation is too big to fit for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test writeable
write to a chunk from Mem_Alloc and check the value

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/writeable
writeable: writeable.c:9: main: Assertion `ptr != ((void *)0)' failed.
test writeable FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/writeable returned incorrect status code. Expected 0 got -6


test writeable FAILED
 (write to a chunk from Mem_Alloc and check the value)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/writeable returned incorrect status code. Expected 0 got -6


**********************************************************************

Test free_simple
a simple allocation followed by a free

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/free_simple
free_simple: free_simple.c:9: main: Assertion `ptr != ((void *)0)' failed.
test free_simple FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_simple returned incorrect status code. Expected 0 got -6


test free_simple FAILED
 (a simple allocation followed by a free)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_simple returned incorrect status code. Expected 0 got -6


**********************************************************************

Test free_null
free a NULL pointer

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/free_null
free_null: free_null.c:9: main: Assertion `ptr != ((void *)0)' failed.
test free_null FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_null returned incorrect status code. Expected 0 got -6


test free_null FAILED
 (free a NULL pointer)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_null returned incorrect status code. Expected 0 got -6


**********************************************************************

Test free_unallocated
free a pointer which does not point to beginning of a block

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/free_unallocated
free_unallocated: free_unallocated.c:9: main: Assertion `ptr != ((void *)0)' failed.
test free_unallocated FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_unallocated returned incorrect status code. Expected 0 got -6


test free_unallocated FAILED
 (free a pointer which does not point to beginning of a block)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_unallocated returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align_bestfit
first pointer returned is 4-byte aligned with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align_bestfit
align_bestfit: align_bestfit.c:10: main: Assertion `ptr != ((void *)0)' failed.
test align_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_bestfit returned incorrect status code. Expected 0 got -6


test align_bestfit FAILED
 (first pointer returned is 4-byte aligned with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align_worstfit
first pointer returned is 4-byte aligned with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align_worstfit
align_worstfit: align_worstfit.c:8: main: Assertion `Mem_Init(4096,1) == 0' failed.
test align_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_worstfit returned incorrect status code. Expected 0 got -6


test align_worstfit FAILED
 (first pointer returned is 4-byte aligned with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align_firstfit
first pointer returned is 4-byte aligned with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align_firstfit
align_firstfit: align_firstfit.c:8: main: Assertion `Mem_Init(4096,2) == 0' failed.
test align_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_firstfit returned incorrect status code. Expected 0 got -6


test align_firstfit FAILED
 (first pointer returned is 4-byte aligned with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_bestfit
a few allocations in multiples of 4 bytes for bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_bestfit
alloc2_bestfit: alloc2_bestfit.c:8: main: Assertion `Mem_Alloc(4) != ((void *)0)' failed.
test alloc2_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_bestfit returned incorrect status code. Expected 0 got -6


test alloc2_bestfit FAILED
 (a few allocations in multiples of 4 bytes for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_worstfit
a few allocations in multiples of 4 bytes for worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_worstfit
alloc2_worstfit: alloc2_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test alloc2_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_worstfit returned incorrect status code. Expected 0 got -6


test alloc2_worstfit FAILED
 (a few allocations in multiples of 4 bytes for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_firstfit
a few allocations in multiples of 4 bytes for firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_firstfit
alloc2_firstfit: alloc2_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test alloc2_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_firstfit returned incorrect status code. Expected 0 got -6


test alloc2_firstfit FAILED
 (a few allocations in multiples of 4 bytes for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_nospace_bestfit
second allocation is too big to fit for bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_bestfit
alloc2_nospace_bestfit: alloc2_nospace_bestfit.c:8: main: Assertion `Mem_Alloc(2048) != ((void *)0)' failed.
test alloc2_nospace_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_bestfit returned incorrect status code. Expected 0 got -6


test alloc2_nospace_bestfit FAILED
 (second allocation is too big to fit for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_nospace_worstfit
second allocation is too big to fit for worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_worstfit
alloc2_nospace_worstfit: alloc2_nospace_worstfit.c:7: main: Assertion `Mem_Init(4096, (1)) == 0' failed.
test alloc2_nospace_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_worstfit returned incorrect status code. Expected 0 got -6


test alloc2_nospace_worstfit FAILED
 (second allocation is too big to fit for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc2_nospace_firstfit
second allocation is too big to fit for firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_firstfit
alloc2_nospace_firstfit: alloc2_nospace_firstfit.c:7: main: Assertion `Mem_Init(4096, (2)) == 0' failed.
test alloc2_nospace_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_firstfit returned incorrect status code. Expected 0 got -6


test alloc2_nospace_firstfit FAILED
 (second allocation is too big to fit for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test free2
a few allocations in multiples of 4 bytes followed by frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/free2


test free2 PASSED
 (a few allocations in multiples of 4 bytes followed by frees)


**********************************************************************

Test align2_bestfit
a few allocations in multiples of 4 bytes checked for alignment with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_bestfit


test align2_bestfit PASSED
 (a few allocations in multiples of 4 bytes checked for alignment with bestfit policy)


**********************************************************************

Test align2_worstfit
a few allocations in multiples of 4 bytes checked for alignment with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_worstfit
align2_worstfit: align2_worstfit.c:8: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test align2_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_worstfit returned incorrect status code. Expected 0 got -6


test align2_worstfit FAILED
 (a few allocations in multiples of 4 bytes checked for alignment with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align2_firstfit
a few allocations in multiples of 4 bytes checked for alignment with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_firstfit
align2_firstfit: align2_firstfit.c:8: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test align2_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_firstfit returned incorrect status code. Expected 0 got -6


test align2_firstfit FAILED
 (a few allocations in multiples of 4 bytes checked for alignment with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc3_bestfit
many odd sized allocations for bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_bestfit
alloc3_bestfit: alloc3_bestfit.c:8: main: Assertion `Mem_Alloc(1) != ((void *)0)' failed.
test alloc3_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_bestfit returned incorrect status code. Expected 0 got -6


test alloc3_bestfit FAILED
 (many odd sized allocations for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc3_worstfit
many odd sized allocations for worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_worstfit
alloc3_worstfit: alloc3_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test alloc3_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_worstfit returned incorrect status code. Expected 0 got -6


test alloc3_worstfit FAILED
 (many odd sized allocations for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test alloc3_firstfit
many odd sized allocations for firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_firstfit
alloc3_firstfit: alloc3_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test alloc3_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_firstfit returned incorrect status code. Expected 0 got -6


test alloc3_firstfit FAILED
 (many odd sized allocations for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test free3
many odd sized allocations and interspersed frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/free3
free3: free3.c:13: main: Assertion `ptr[0] != ((void *)0)' failed.
test free3 FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/free3 returned incorrect status code. Expected 0 got -6


test free3 FAILED
 (many odd sized allocations and interspersed frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free3 returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align3_bestfit
many odd sized allocations checked for alignment with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_bestfit


test align3_bestfit PASSED
 (many odd sized allocations checked for alignment with bestfit policy)


**********************************************************************

Test align3_worstfit
many odd sized allocations checked for alignment with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_worstfit
align3_worstfit: align3_worstfit.c:8: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test align3_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_worstfit returned incorrect status code. Expected 0 got -6


test align3_worstfit FAILED
 (many odd sized allocations checked for alignment with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test align3_firstfit
many odd sized allocations checked for alignment with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_firstfit
align3_firstfit: align3_firstfit.c:8: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test align3_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_firstfit returned incorrect status code. Expected 0 got -6


test align3_firstfit FAILED
 (many odd sized allocations checked for alignment with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test bestfit
Check for bestfit implementation

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/bestfit
bestfit: bestfit.c:12: main: Assertion `ptr[0] != ((void *)0)' failed.
test bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/bestfit returned incorrect status code. Expected 0 got -6


test bestfit FAILED
 (Check for bestfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test worstfit
Check for worstfit implementation

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/worstfit
worstfit: worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/worstfit returned incorrect status code. Expected 0 got -6


test worstfit FAILED
 (Check for worstfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test firstfit
Check for firstfit implementation

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/firstfit
firstfit: firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/firstfit returned incorrect status code. Expected 0 got -6


test firstfit FAILED
 (Check for firstfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce1_bestfit
check for coalesce free space with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_bestfit
coalesce1_bestfit: coalesce1_bestfit.c:11: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce1_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_bestfit returned incorrect status code. Expected 0 got -6


test coalesce1_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce2_bestfit
check for coalesce free space with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_bestfit
coalesce2_bestfit: coalesce2_bestfit.c:11: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce2_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_bestfit returned incorrect status code. Expected 0 got -6


test coalesce2_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce3_bestfit
check for coalesce free space with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_bestfit
coalesce3_bestfit: coalesce3_bestfit.c:11: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce3_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_bestfit returned incorrect status code. Expected 0 got -6


test coalesce3_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce4_bestfit
check for coalesce free space with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_bestfit
coalesce4_bestfit: coalesce4_bestfit.c:11: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce4_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_bestfit returned incorrect status code. Expected 0 got -6


test coalesce4_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce5_bestfit
check for coalesce free space (first chunk) with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_bestfit
coalesce5_bestfit: coalesce5_bestfit.c:11: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce5_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_bestfit returned incorrect status code. Expected 0 got -6


test coalesce5_bestfit FAILED
 (check for coalesce free space (first chunk) with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce6_bestfit
check for coalesce free space (last chunk) with bestfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_bestfit
coalesce6_bestfit: coalesce6_bestfit.c:14: main: Assertion `ptr[0] != ((void *)0)' failed.
test coalesce6_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_bestfit returned incorrect status code. Expected 0 got -6


test coalesce6_bestfit FAILED
 (check for coalesce free space (last chunk) with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_bestfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce1_worstfit
check for coalesce free space with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_worstfit
coalesce1_worstfit: coalesce1_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce1_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_worstfit returned incorrect status code. Expected 0 got -6


test coalesce1_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce2_worstfit
check for coalesce free space with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_worstfit
coalesce2_worstfit: coalesce2_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce2_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_worstfit returned incorrect status code. Expected 0 got -6


test coalesce2_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce3_worstfit
check for coalesce free space with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_worstfit
coalesce3_worstfit: coalesce3_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce3_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_worstfit returned incorrect status code. Expected 0 got -6


test coalesce3_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce4_worstfit
check for coalesce free space with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_worstfit
coalesce4_worstfit: coalesce4_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce4_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_worstfit returned incorrect status code. Expected 0 got -6


test coalesce4_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce5_worstfit
check for coalesce free space (first chunk) with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_worstfit
coalesce5_worstfit: coalesce5_worstfit.c:7: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce5_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_worstfit returned incorrect status code. Expected 0 got -6


test coalesce5_worstfit FAILED
 (check for coalesce free space (first chunk) with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce6_worstfit
check for coalesce free space (last chunk) with worstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_worstfit
coalesce6_worstfit: coalesce6_worstfit.c:10: main: Assertion `Mem_Init(4096,(1)) == 0' failed.
test coalesce6_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_worstfit returned incorrect status code. Expected 0 got -6


test coalesce6_worstfit FAILED
 (check for coalesce free space (last chunk) with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_worstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce1_firstfit
check for coalesce free space with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_firstfit
coalesce1_firstfit: coalesce1_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce1_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_firstfit returned incorrect status code. Expected 0 got -6


test coalesce1_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce2_firstfit
check for coalesce free space with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_firstfit
coalesce2_firstfit: coalesce2_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce2_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_firstfit returned incorrect status code. Expected 0 got -6


test coalesce2_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce3_firstfit
check for coalesce free space with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_firstfit
coalesce3_firstfit: coalesce3_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce3_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_firstfit returned incorrect status code. Expected 0 got -6


test coalesce3_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce4_firstfit
check for coalesce free space with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_firstfit
coalesce4_firstfit: coalesce4_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce4_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_firstfit returned incorrect status code. Expected 0 got -6


test coalesce4_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce5_firstfit
check for coalesce free space (first chunk) with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_firstfit
coalesce5_firstfit: coalesce5_firstfit.c:7: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce5_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_firstfit returned incorrect status code. Expected 0 got -6


test coalesce5_firstfit FAILED
 (check for coalesce free space (first chunk) with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test coalesce6_firstfit
check for coalesce free space (last chunk) with firstfit policy

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_firstfit
coalesce6_firstfit: coalesce6_firstfit.c:10: main: Assertion `Mem_Init(4096,(2)) == 0' failed.
test coalesce6_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/ctest.py", line 9, in run
    self.runexe([os.path.join(self.path, self.name)] + self.args, status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_firstfit returned incorrect status code. Expected 0 got -6


test coalesce6_firstfit FAILED
 (check for coalesce free space (last chunk) with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_firstfit returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random1_bestfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 0
test random1_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


test random1_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


**********************************************************************

Test random2_bestfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 0
test random2_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


test random2_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


**********************************************************************

Test random3_bestfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 100000 1 0
test random3_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


test random3_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


**********************************************************************

Test random4_bestfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 500000 1 0
test random4_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


test random4_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11


**********************************************************************

Test random1_worstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 1
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random1_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random1_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random2_worstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 1
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random2_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random2_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random3_worstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 100000 1 1
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random3_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random3_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random4_worstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 500000 1 1
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random4_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random4_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random1_firstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 2
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random1_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random1_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random2_firstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 1000 1 2
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random2_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random2_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random3_firstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 0 100000 1 2
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random3_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random3_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random4_firstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 500000 1 2
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random4_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random4_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random5_bestfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 20000000 0 0
random: random.c:71: main: Assertion `Mem_Free(ptr[slot]) == -1' failed.
test random5_bestfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random5_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random5_worstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 20000000 0 1
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random5_worstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random5_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test random5_firstfit
psuedo-random sequence of allocs and frees

**********************************************************************
/u/c/s/cs354-3/ta/p3/UserScripts/random 1 20000000 0 2
random: random.c:55: main: Assertion `Mem_Init((region_size + slack),policy) == 0' failed.
test random5_firstfit FAILED
Traceback (most recent call last):
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 183, in run_test
    test.run()
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/rand.py", line 14, in run
    status = 0)
  File "/afs/cs.wisc.edu/p/course/cs354-remzi/ta/p3/UserScripts/test.py", line 112, in runexe
    "Expected " + str(status) + " got " + str(child.returncode))
Failure: /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


test random5_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6


**********************************************************************

Test prohibit
check for prohibited library functions

**********************************************************************
objdump --dynamic-syms libmem.so


test prohibit PASSED
 (check for prohibited library functions)

**********************************************************************
Summary:
test build FAILED
 (build project using make)
 make clean failed (error 2)
 make failed (error 2)

test init_bestfit PASSED
 (call Mem_Init with size = 1 page and policy = P_BESTFIT)

test init_worstfit FAILED
 (call Mem_Init with size = 5 pages and policy = P_WORSTFIT)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_worstfit returned incorrect status code. Expected 0 got -6

test init_firstfit FAILED
 (call Mem_Init with size = 10 pages and policy = P_FIRSTFIT)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_firstfit returned incorrect status code. Expected 0 got -6

test init_pageround PASSED
 (init that should be rounded up to 1 page)

test init_zerosize PASSED
 (call Mem_Init with zero size)

test init_negsize PASSED
 (call Mem_Init with negative size)

test init_negpolicy PASSED
 (call Mem_Init with a negative policy)

test init_badpolicy PASSED
 (call Mem_Init with an invalid positive policy)

test init_twice FAILED
 (call Mem_Init twice)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/init_twice returned incorrect status code. Expected 0 got -6

test alloc_bestfit FAILED
 (a simple 8 byte allocation with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_bestfit returned incorrect status code. Expected 0 got -6

test alloc_worstfit FAILED
 (a simple 8 byte allocation with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_worstfit returned incorrect status code. Expected 0 got -6

test alloc_firstfit FAILED
 (a simple 8 byte allocation with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_firstfit returned incorrect status code. Expected 0 got -6

test alloc_nospace_bestfit PASSED
 (allocation is too big to fit for bestfit policy)

test alloc_nospace_worstfit FAILED
 (allocation is too big to fit for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_worstfit returned incorrect status code. Expected 0 got -6

test alloc_nospace_firstfit FAILED
 (allocation is too big to fit for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc_nospace_firstfit returned incorrect status code. Expected 0 got -6

test writeable FAILED
 (write to a chunk from Mem_Alloc and check the value)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/writeable returned incorrect status code. Expected 0 got -6

test free_simple FAILED
 (a simple allocation followed by a free)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_simple returned incorrect status code. Expected 0 got -6

test free_null FAILED
 (free a NULL pointer)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_null returned incorrect status code. Expected 0 got -6

test free_unallocated FAILED
 (free a pointer which does not point to beginning of a block)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free_unallocated returned incorrect status code. Expected 0 got -6

test align_bestfit FAILED
 (first pointer returned is 4-byte aligned with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_bestfit returned incorrect status code. Expected 0 got -6

test align_worstfit FAILED
 (first pointer returned is 4-byte aligned with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_worstfit returned incorrect status code. Expected 0 got -6

test align_firstfit FAILED
 (first pointer returned is 4-byte aligned with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align_firstfit returned incorrect status code. Expected 0 got -6

test alloc2_bestfit FAILED
 (a few allocations in multiples of 4 bytes for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_bestfit returned incorrect status code. Expected 0 got -6

test alloc2_worstfit FAILED
 (a few allocations in multiples of 4 bytes for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_worstfit returned incorrect status code. Expected 0 got -6

test alloc2_firstfit FAILED
 (a few allocations in multiples of 4 bytes for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_firstfit returned incorrect status code. Expected 0 got -6

test alloc2_nospace_bestfit FAILED
 (second allocation is too big to fit for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_bestfit returned incorrect status code. Expected 0 got -6

test alloc2_nospace_worstfit FAILED
 (second allocation is too big to fit for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_worstfit returned incorrect status code. Expected 0 got -6

test alloc2_nospace_firstfit FAILED
 (second allocation is too big to fit for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc2_nospace_firstfit returned incorrect status code. Expected 0 got -6

test free2 PASSED
 (a few allocations in multiples of 4 bytes followed by frees)

test align2_bestfit PASSED
 (a few allocations in multiples of 4 bytes checked for alignment with bestfit policy)

test align2_worstfit FAILED
 (a few allocations in multiples of 4 bytes checked for alignment with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_worstfit returned incorrect status code. Expected 0 got -6

test align2_firstfit FAILED
 (a few allocations in multiples of 4 bytes checked for alignment with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align2_firstfit returned incorrect status code. Expected 0 got -6

test alloc3_bestfit FAILED
 (many odd sized allocations for bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_bestfit returned incorrect status code. Expected 0 got -6

test alloc3_worstfit FAILED
 (many odd sized allocations for worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_worstfit returned incorrect status code. Expected 0 got -6

test alloc3_firstfit FAILED
 (many odd sized allocations for firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/alloc3_firstfit returned incorrect status code. Expected 0 got -6

test free3 FAILED
 (many odd sized allocations and interspersed frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/free3 returned incorrect status code. Expected 0 got -6

test align3_bestfit PASSED
 (many odd sized allocations checked for alignment with bestfit policy)

test align3_worstfit FAILED
 (many odd sized allocations checked for alignment with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_worstfit returned incorrect status code. Expected 0 got -6

test align3_firstfit FAILED
 (many odd sized allocations checked for alignment with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/align3_firstfit returned incorrect status code. Expected 0 got -6

test bestfit FAILED
 (Check for bestfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/bestfit returned incorrect status code. Expected 0 got -6

test worstfit FAILED
 (Check for worstfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/worstfit returned incorrect status code. Expected 0 got -6

test firstfit FAILED
 (Check for firstfit implementation)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/firstfit returned incorrect status code. Expected 0 got -6

test coalesce1_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_bestfit returned incorrect status code. Expected 0 got -6

test coalesce2_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_bestfit returned incorrect status code. Expected 0 got -6

test coalesce3_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_bestfit returned incorrect status code. Expected 0 got -6

test coalesce4_bestfit FAILED
 (check for coalesce free space with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_bestfit returned incorrect status code. Expected 0 got -6

test coalesce5_bestfit FAILED
 (check for coalesce free space (first chunk) with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_bestfit returned incorrect status code. Expected 0 got -6

test coalesce6_bestfit FAILED
 (check for coalesce free space (last chunk) with bestfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_bestfit returned incorrect status code. Expected 0 got -6

test coalesce1_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_worstfit returned incorrect status code. Expected 0 got -6

test coalesce2_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_worstfit returned incorrect status code. Expected 0 got -6

test coalesce3_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_worstfit returned incorrect status code. Expected 0 got -6

test coalesce4_worstfit FAILED
 (check for coalesce free space with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_worstfit returned incorrect status code. Expected 0 got -6

test coalesce5_worstfit FAILED
 (check for coalesce free space (first chunk) with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_worstfit returned incorrect status code. Expected 0 got -6

test coalesce6_worstfit FAILED
 (check for coalesce free space (last chunk) with worstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_worstfit returned incorrect status code. Expected 0 got -6

test coalesce1_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce1_firstfit returned incorrect status code. Expected 0 got -6

test coalesce2_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce2_firstfit returned incorrect status code. Expected 0 got -6

test coalesce3_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce3_firstfit returned incorrect status code. Expected 0 got -6

test coalesce4_firstfit FAILED
 (check for coalesce free space with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce4_firstfit returned incorrect status code. Expected 0 got -6

test coalesce5_firstfit FAILED
 (check for coalesce free space (first chunk) with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce5_firstfit returned incorrect status code. Expected 0 got -6

test coalesce6_firstfit FAILED
 (check for coalesce free space (last chunk) with firstfit policy)
 /u/c/s/cs354-3/ta/p3/UserScripts/tests/coalesce6_firstfit returned incorrect status code. Expected 0 got -6

test random1_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11

test random2_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11

test random3_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11

test random4_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -11

test random1_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random2_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random3_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random4_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random1_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random2_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random3_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random4_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random5_bestfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random5_worstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test random5_firstfit FAILED
 (psuedo-random sequence of allocs and frees)
 /u/c/s/cs354-3/ta/p3/UserScripts/random returned incorrect status code. Expected 0 got -6

test prohibit PASSED
 (check for prohibited library functions)

Passed 11 of 77 tests.
Overall 11 of 77
